### PR TITLE
Corrected support for de-CH and de-LI

### PR DESCRIPTION
**Pull request by mbuehrig**
Added a new function (apostrophThousDotDec) for correct swiss locale separating.

### CODE REVIEW

**Comment by willsp** [comment]
Thanks!

**Comment by davidknezic** [comment]
Are you going to publish a new version on npm @willsp?

**Comment by willsp** [comment]
Yea, I've got one more pull request that has some simple conflicts. I'll be straightening them out then I'll push an update to npm.

**Comment by davidknezic** [comment]
Awesome, thank you! :)

**Comment by willsp** [comment]
Version 1.0.1 is published.

**Pull request merged**
