### PR TITLE
Handle not supported currency symbols by showing code in uppercase

### PR DESCRIPTION
**Pull request by tantawyk**
This commit is to handle cases where the currency symbol doesn't
exist in the map e.g. bitcoin and new crypto currencies

### CODE REVIEW

**Comment by khaled-cliqz** [comment]
@willsp, please take a look on this PR, all tests are passing.

**Comment by willsp** [comment]
Nice!

**Comment by willsp** [comment]
I'll ship an update to npm shortly...

**Comment by tantawyk** [comment]
@willsp thanks :)

**Pull request merged**
